---
- name: installs docker package(s)
  hosts: all
  remote_user: vagrant
  become: true
  vars:
    - config_docker_users: true  #defines if users should be added to docker group to allow non sudo access to docker
    - configure_firewall: false
    - docker_images:
      - image: ubuntu
        state: present
    - docker_opts:  #defines docker service options to be configured
      - '--dns {{ pri_dns }}'
      - '--dns {{ sec_dns }}'
#      - '--insecure-registry 192.168.202.34:5000'
      - '-H tcp://0.0.0.0:2375'
      - '-H unix:///var/run/docker.sock'
    - docker_users:
        - vagrant
    - pri_dns: 8.8.8.8  #defines primary dns server for your site
    - sec_dns: 8.8.4.4  #defines secondary dns server for your site
    - ufw_policies:  #defines default policy for incoming, outgoing and routed (forwarded) traffic...allow, deny or reject
      - direction: incoming
        policy: deny
      - direction: outgoing
        policy: allow
      - direction: routed
        policy: allow
    - ufw_rules:
      - rule: limit
        proto: tcp
        to_port: 22
      - rule: allow
        proto: tcp
        to_port: 2375
  roles:
    - role: ansible-docker
    - role: ansible-ufw
      when: configure_firewall is defined and configure_firewall
  tasks:
