---
docker_images:
  - image: ubuntu
    state: present
docker_opts:  #defines docker service options to be configured
  - '--dns {{ pri_dns }}'
  - '--dns {{ sec_dns }}'
  - '--insecure-registry 192.168.202.34:5000'
pri_dns: 8.8.8.8  #defines primary dns server for your site
sec_dns: 8.8.4.4  #defines secondary dns server for your site
