---
ufw_policies:  #defines default policy for incoming, outgoing and routed (forwarded) traffic...allow, deny or reject
  - direction: incoming
    policy: deny
  - direction: outgoing
    policy: allow
  - direction: routed
    policy: allow
ufw_rules:
 - rule: limit
   proto: tcp
   to_port: 22
 - rule: allow
   proto: tcp
   to_port: 2375
 - rule: allow
   proto: tcp
   to_port: 9200
 - rule: allow
   proto: tcp
   to_port: 9300
 - rule: allow
   proto: udp
   to_port: 54328
